// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reputy.Application.DatabaseContext;

#nullable disable

namespace Reputy.Application.Migrations
{
    [DbContext(typeof(ReputyContext))]
    partial class ReputyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reputy.Domain.Entities.Advertisement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<decimal?>("Deposit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasAnnotation("Relational:JsonPropertyName", "deposit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "image_urls");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isShared");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "pets_allowed");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasAnnotation("Relational:JsonPropertyName", "price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Advertisements");

                    b.HasAnnotation("Relational:JsonPropertyName", "advertisement");

                    b.HasData(
                        new
                        {
                            ID = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "Náměstí Míru 5, Praha",
                            CreatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4315),
                            Deposit = 5000m,
                            ImageUrls = "[]",
                            IsShared = true,
                            PetsAllowed = true,
                            Price = 15000m,
                            Title = "Moderní byt v centru",
                            UpdatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4316),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ID = new Guid("77777777-7777-7777-7777-777777777777"),
                            Address = "Rašínovo nábřeží 12, Praha 2",
                            CreatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4321),
                            Deposit = 6000m,
                            ImageUrls = "[]",
                            IsShared = false,
                            PetsAllowed = false,
                            Price = 18000m,
                            Title = "Byt 2+KK s výhledem na řeku",
                            UpdatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4322),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ID = new Guid("88888888-8888-8888-8888-888888888888"),
                            Address = "U školy 45, Brno",
                            CreatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4336),
                            Deposit = 8000m,
                            ImageUrls = "[]",
                            IsShared = false,
                            PetsAllowed = true,
                            Price = 22000m,
                            Title = "Velký byt 3+1 pro rodinu",
                            UpdatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4337),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Reputy.Domain.Entities.AdvertisementRealEstate", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<Guid>("AdvertisementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<int>("Disposition")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "disposition");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<int>("RentalType")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "rentalType");

                    b.Property<decimal>("Size")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasAnnotation("Relational:JsonPropertyName", "size");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("ID");

                    b.HasIndex("AdvertisementId")
                        .IsUnique();

                    b.ToTable("AdvertisementRealEstates");

                    b.HasAnnotation("Relational:JsonPropertyName", "realEstate");

                    b.HasData(
                        new
                        {
                            ID = new Guid("b995b9ec-7e5c-4342-9825-b89db062d30b"),
                            AdvertisementId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4359),
                            Disposition = 2,
                            Location = "Praha 1",
                            RentalType = 2,
                            Size = 30.0m,
                            UpdatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4360)
                        },
                        new
                        {
                            ID = new Guid("99999999-9999-9999-9999-999999999999"),
                            AdvertisementId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4364),
                            Disposition = 4,
                            Location = "Praha 2",
                            RentalType = 1,
                            Size = 40.0m,
                            UpdatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4365)
                        },
                        new
                        {
                            ID = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AdvertisementId = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4369),
                            Disposition = 5,
                            Location = "Brno",
                            RentalType = 1,
                            Size = 85.0m,
                            UpdatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4370)
                        });
                });

            modelBuilder.Entity("Reputy.Domain.Entities.Reference", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<Guid>("FromUserID")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "from_user_id");

                    b.Property<decimal>("Rating")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasAnnotation("Relational:JsonPropertyName", "rating");

                    b.Property<Guid>("RentalID")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "rental_id");

                    b.Property<Guid>("ToUserID")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "to_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("ID");

                    b.HasIndex("FromUserID");

                    b.HasIndex("RentalID");

                    b.HasIndex("ToUserID");

                    b.ToTable("References");

                    b.HasAnnotation("Relational:JsonPropertyName", "references_received");

                    b.HasData(
                        new
                        {
                            ID = new Guid("55555555-5555-5555-5555-555555555555"),
                            Comment = "Velmi spolehlivý pronajímatel",
                            CreatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4413),
                            FromUserID = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rating = 5m,
                            RentalID = new Guid("44444444-4444-4444-4444-444444444444"),
                            ToUserID = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4414)
                        });
                });

            modelBuilder.Entity("Reputy.Domain.Entities.Rental", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<Guid>("AdvertisementID")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "advertisement_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "end_date");

                    b.Property<Guid>("LandlordId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "landlord_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "start_date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("ID");

                    b.HasIndex("AdvertisementID");

                    b.HasIndex("LandlordId");

                    b.HasIndex("TenantId");

                    b.ToTable("Rentals");

                    b.HasAnnotation("Relational:JsonPropertyName", "rentals_tenant");

                    b.HasData(
                        new
                        {
                            ID = new Guid("44444444-4444-4444-4444-444444444444"),
                            AdvertisementID = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4394),
                            EndDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            LandlordId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartDate = new DateTime(2025, 6, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 2,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4395)
                        });
                });

            modelBuilder.Entity("Reputy.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("Av")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "firstName");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "avatar_url");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "averageRating");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "firstName");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isVerified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "LastName");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "role");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasAnnotation("Relational:JsonPropertyName", "tenant");

                    b.HasData(
                        new
                        {
                            ID = new Guid("11111111-1111-1111-1111-111111111111"),
                            Av = 0,
                            AvatarUrl = "https://example.com/avatar1.png",
                            AverageRating = 0m,
                            CreatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4149),
                            Email = "jan.novak@example.com",
                            FirstName = "Jan",
                            IsVerified = true,
                            LastName = "Novak",
                            Password = "hashedpassword1",
                            Role = 2,
                            UpdatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4152)
                        },
                        new
                        {
                            ID = new Guid("22222222-2222-2222-2222-222222222222"),
                            Av = 0,
                            AverageRating = 0m,
                            CreatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4158),
                            Email = "eva.svobodova@example.com",
                            FirstName = "Eva",
                            IsVerified = false,
                            LastName = "Svobodova",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 6, 27, 13, 59, 52, 265, DateTimeKind.Local).AddTicks(4159)
                        });
                });

            modelBuilder.Entity("Reputy.Domain.Entities.Advertisement", b =>
                {
                    b.HasOne("Reputy.Domain.Entities.User", "Landlord")
                        .WithMany("Advertisements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("Reputy.Domain.Entities.AdvertisementRealEstate", b =>
                {
                    b.HasOne("Reputy.Domain.Entities.Advertisement", "Advertisement")
                        .WithOne("AdvertisementRealEstate")
                        .HasForeignKey("Reputy.Domain.Entities.AdvertisementRealEstate", "AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("Reputy.Domain.Entities.Reference", b =>
                {
                    b.HasOne("Reputy.Domain.Entities.User", "FromUser")
                        .WithMany("ReferencesWritten")
                        .HasForeignKey("FromUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reputy.Domain.Entities.Rental", "Rental")
                        .WithMany()
                        .HasForeignKey("RentalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reputy.Domain.Entities.User", "ToUser")
                        .WithMany("ReferencesReceived")
                        .HasForeignKey("ToUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("Rental");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Reputy.Domain.Entities.Rental", b =>
                {
                    b.HasOne("Reputy.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany()
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reputy.Domain.Entities.User", "Landlord")
                        .WithMany("RentalsAsLandlord")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reputy.Domain.Entities.User", "Tenant")
                        .WithMany("RentalsAsTenant")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("Landlord");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Reputy.Domain.Entities.Advertisement", b =>
                {
                    b.Navigation("AdvertisementRealEstate")
                        .IsRequired();
                });

            modelBuilder.Entity("Reputy.Domain.Entities.User", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("ReferencesReceived");

                    b.Navigation("ReferencesWritten");

                    b.Navigation("RentalsAsLandlord");

                    b.Navigation("RentalsAsTenant");
                });
#pragma warning restore 612, 618
        }
    }
}
